Minutos de la reunión de agosto 2019
carpentries/latinoamerica pull request #15
Opened 2019-08-09 18:52 UTC by dpshelio

@flor14 @raynamharris @lauracion @npalopoli @agbeltran @luspairani 

Revisen y sugieran si faltó algo.

@raynamharris eres increible, escribes super bien! Sólo te faltó alguna ñ :open_mouth:

2019-08-10 11:46 UTC, lauracion commented
Muchas gracias, @raynamharris y @dpshelio! Lujo de equipo ☺️

2019-08-12 05:55 UTC, orchid00 requested changes
great updates guys!

2019-08-12 05:55 UTC, orchid00 commented on traducciones/minutos/2019-08-08.md
> +   -  U. de Quilmes. [Programación con python](
```suggestion
   -  U. de Quilmes. [Programación con Python](
```

2019-08-12 05:55 UTC, orchid00 commented on traducciones/minutos/2019-08-08.md
> +      importante que hay maintainers y traductores, y a poder ser que no sean
```suggestion
      importante que haya maintainers y traductores, y estos pueden ser 
```

2019-08-12 05:55 UTC, orchid00 commented on traducciones/minutos/2019-08-08.md
> +   -  necesita instructores y ayudantes
```suggestion
   -  necesitamos instructores y ayudantes
```

2019-08-12 05:55 UTC, orchid00 commented on traducciones/minutos/2019-08-08.md
> +       - Y si usa el de data carpentry, podemos enfocar en tranducir los datos
```suggestion
       - Y si usa la de data carpentry, podemos enfocarnos en tranducir los datos
```

2019-08-12 05:55 UTC, orchid00 commented on traducciones/minutos/2019-08-08.md
> +  Rayna va a preguntar y slack por ayudantes.
```suggestion
  Rayna va a preguntar en slack por ayudantes.
```

2019-08-12 05:55 UTC, orchid00 commented on traducciones/minutos/2019-08-08.md
> +   - falta traducir la material de train the trainer - Laura se encarga.
```suggestion
   - falta traducir el material de train the trainer - Laura se encargara.
```

2019-08-12 05:55 UTC, orchid00 commented on traducciones/minutos/2019-08-08.md
> +   - tal vez, podemos enseñar el training y traducir los en un group de gente -
```suggestion
   - tal vez, podemos enseñar el training y traducirlo con en un grupo de gente -
```

2019-08-12 05:55 UTC, orchid00 commented on traducciones/minutos/2019-08-08.md
> +  viven - Rayna tiene un update. Publicar lo que hablar cada uno no es posible
```suggestion
  viven - Rayna tiene un update. Publicar el idioma que cada uno habla no es posible
```

2019-08-12 05:55 UTC, orchid00 commented on traducciones/minutos/2019-08-08.md
> +  (aunque registratod en AMY) por no tener el consentimiento de los instructores
```suggestion
  (aunque esta registrato en AMY) se necesita el consentimiento de los instructores
```

2019-08-12 05:55 UTC, orchid00 commented on traducciones/minutos/2019-08-08.md
> +- *Laura***
```suggestion
- **Laura**
```

2019-09-26 07:10 UTC, orchid00 commented
@dpshelio puedes revisar?

2019-10-03 12:06 UTC, orchid00 commented
@lauracion @npalopoli lo revisan?

2020-01-07 02:19 UTC, orchid00 approved these changes

2020-01-07 02:19 UTC, merged