Actualización de instrucciones sobre traducción 2019/2020
carpentries/latinoamerica pull request #17
Opened 2020-01-20 20:14 UTC by LUS24

Hola!, envío propuesta sobre instrucciones para traducción.

2020-01-21 12:05 UTC, dpshelio requested changes
Gracias @LUS24! Buen trabajo!!
He añadido unos pequeños comentarios.

2020-01-21 12:05 UTC, dpshelio commented on traducciones/2019_instrucciones.md
> +3. Ingresar al [canal de Riot de Carpentries_ES](https://matrix.to/#/!DiYhyKboywrDdhLjXH:matrix.org?via=matrix.org&via=petrichor.me)
```suggestion
3. Ingresar al [canal de Riot de Carpentries_ES](https://matrix.to/#/!DiYhyKboywrDdhLjXH:matrix.org?via=matrix.org&via=petrichor.me) o accediendo al canal del mismo nombre dentro del [equipo de slack de las Carpentries](https://swcarpentry.slack.com) ([auto-invítate si no tienes acceso](https://swc-slack-invite.herokuapp.com/))
```

2020-01-21 12:05 UTC, dpshelio commented on traducciones/2019_instrucciones.md
> +5. A la brevedad se te avisará que ya está todo habilitado como para que empieces a traducir o revisar el material.
```suggestion

A la brevedad se te avisará que ya está todo habilitado como para que empieces a traducir o revisar el material.
```

2020-01-21 12:05 UTC, dpshelio commented on traducciones/2019_instrucciones.md
> +Una vez cumplidos los requisitos, ingresar al tablero de Trello que usamos para coordinar las traducciones a travez de [este link](https://trello.com/invite/b/8weO4xoS/b3d61bf7fcd3c7d0567201c20142bb1
```suggestion
Una vez cumplidos los requisitos, ingresa [al tablero de Trello que usamos para coordinar las traducciones](https://trello.com/invite/b/8weO4xoS/b3d61bf7fcd3c7d0567201c20142bb13/notebook-translation-es). En caso de que el enlace no se encuentre activo, notifícanos mediante el canal de Riot/Slack.
```

2020-01-21 12:05 UTC, dpshelio commented on traducciones/2019_instrucciones.md
> +f. **Revisión final**: es el último proceso de revisión antes de que el material sea subido al repositorio para se pueso en producción.
```suggestion
f. **Revisión final**: es el último proceso de revisión antes de que el material sea subido al repositorio para que se publique.
```

2020-01-21 12:05 UTC, dpshelio commented on traducciones/2019_instrucciones.md
> +g. **Con observaciones**: aquí se ubican las tarjetas que luego de su revisión todavía necesan ciertas modificaciones.
```suggestion
g. **Con observaciones**: aquí se ubican las tarjetas que luego de su revisión todavía necesitan ciertas modificaciones.
```

2020-01-21 12:05 UTC, dpshelio commented on traducciones/2019_instrucciones.md
> + Para empezar, haz click sobre la tarjeta dentro de la lista, se abrirá una lista con todos los recursos correspondientes a una sección en particular del material que está siendo traducido. Haz click
sobre... ??

2020-01-21 12:05 UTC, dpshelio commented on traducciones/2019_instrucciones.md
> +2. Una vez que estés en la plataforma Transifex, fíjate en el historial que nadie esté trabajando en el recurso activamente así evitaremos superponernos en las tareas.
Lo bueno de transifex es que muchos pueden trabajar en el mismo archivo. No así en el mismo fragmento de texto, pero no creo que esta limitación sea completamente necesaria. Aunque, habiendo dicho esto, es mejor que la misma persona trabaje en el mismo archivo para que haya una mejor continuidad.

2020-01-21 12:05 UTC, dpshelio commented on traducciones/2019_instrucciones.md
> +1. Ve a la lista **d**, **e** o **f** y sigue los mismos pasos como si fuera una traducción.
```suggestion
1. Ve a la lista **d**, **e** o **f** y sigue los mismos pasos como si fuera una traducción.
1. En Transifex, por cada fragmento que hayas revisado márcalo como tal (botón al lado de guardar cambios en el cuadro de traducción). Si te gustaría hacer un comentario a dicha traducción, hazlo pinchando en la sección de comentarios (a la derecha de la pantalla).
```

2020-01-21 12:16 UTC, lauracion commented on traducciones/2019_instrucciones.md
> +3. Ingresar al [canal de Riot de Carpentries_ES](https://matrix.to/#/!DiYhyKboywrDdhLjXH:matrix.org?via=matrix.org&via=petrichor.me)
Aquí agregaría también el link para unirse al Slack de The Carpentries y al canal #carpentries_es, no? Sé que Riot abarca esto. Pero me parece que sumar a la gente al Slack general de The Carpentries hace que de a poco sean parte de la comunidad global tambien

2020-01-21 12:16 UTC, lauracion commented on traducciones/2019_instrucciones.md
> +4. Notificar a Leonardo Spairani (usuario de Riot / Slack @leonardo_spai) para solicitar acceso a la plataforma de traducción y al tablero de Trello.
También pueden arrobarme a mí y a las demás personas que están como organizadoras en Transifex - así no te cargás vos solo :smiley_cat:

2020-01-21 12:16 UTC, lauracion commented on traducciones/2019_instrucciones.md
> +5. A la brevedad se te avisará que ya está todo habilitado como para que empieces a traducir o revisar el material.
Como esto es trabajo voluntario, quizás eliminaría la mención de "A la brevedad" y diría "Lo más pronto que podamos" o algo así. Como para que la gente que espera una respuesta inmediata y no la obtiene no se frustre.

2020-01-21 12:16 UTC, lauracion commented on traducciones/2019_instrucciones.md
> +Una vez cumplidos los requisitos, ingresar al tablero de Trello que usamos para coordinar las traducciones a travez de [este link](https://trello.com/invite/b/8weO4xoS/b3d61bf7fcd3c7d0567201c20142bb1
"travez" debería ser "través"

2020-01-21 12:16 UTC, lauracion commented on traducciones/2019_instrucciones.md
> +
Entiendo que esto puede ser útil para tener de un vistazo el estado de cosas. Sin embargo, también veo que parte de esta tarea ya la hace Transifex por nosotres. Por eso estoy un poco dividida con este procedimiento. Por otro lado, se plantean tres revisiones de todo (revisión 1, revisión 2 y revisión final) - es así cómo se hizo con las otras traducciones? Me inclino a pensar que con la revisión 1 que administra Transifex y una última revisión general podría ya pasarse al siguiente paso. Quizás esto sería bueno charlarlo en la próxima reunión.

No hay que perder de vista que las últimas revisiones se irán dando a través de pull requests con el uso - como se hace con el resto de las lecciones de The Carpentries.

2020-01-21 12:16 UTC, lauracion commented on traducciones/2019_instrucciones.md
> +
Estas dos secciones me gustan mucho!

2020-01-22 01:32 UTC, LUS24 commented on traducciones/2019_instrucciones.md
> +
Dale, como gusten, a mi me pasó que encontré algunas inconsistencias incluso en la versión revisada 2 veces. La revisión final debe ser muy a conciencia.

2020-01-23 04:36 UTC, LUS24 commented on traducciones/2019_instrucciones.md
> +4. Notificar a Leonardo Spairani (usuario de Riot / Slack @leonardo_spai) para solicitar acceso a la plataforma de traducción y al tablero de Trello.
Ahí te agregué a vos también :-)

2020-02-16 13:18 UTC, dpshelio commented
:+1:  a que esto se accepte. Antes lo hagamos mejor podemos referirnos al proceso.

2020-02-16 15:18 UTC, LUS24 commented on traducciones/2019_instrucciones.md
> +Una vez cumplidos los requisitos, ingresar al tablero de Trello que usamos para coordinar las traducciones a travez de [este link](https://trello.com/invite/b/8weO4xoS/b3d61bf7fcd3c7d0567201c20142bb1
Arreglado

2020-03-11 14:11 UTC, dpshelio commented
@orchid00 esto se podría aceptar ya? Se ha revisado ya por dos.

2020-05-11 05:50 UTC, merged

2020-05-11 05:50 UTC, orchid00 commented
Disculpen la tardanza, se me paso desapercibido